### ISSUE TITLE
The Notification Center window name is locale dependent

### ISSUE THREAD

**Issue by hanselsin** [dustinsterk/AirPlayNotification-AutoApprove#1]
Just realized that the window name of Notification Center app is locale specific, I changed my Mac to UK and the window name becomes "Notification Centre" (instead of US spelling of cent-e-r), which caused the script failed to identify the system event window. Same situation applies to locale set to Hong Kong, which uses British spelling.

I tried to set the locale to Japan, the window name is still "Notification Center" so the script works normally. Didn't try European locale but I suspect they all change the spelling of the window title somehow. 

Wonder if there is a way to retrieve the system dictionary to translate the proper window name?

**Comment by dustinsterk** [comment]
Oh interesting.  Good catch!  

I assume it could be updated to take into local set language:

set userLocale to user locale of (system info)

if userLocale is "en_US" then
...
else if userLocale is "es_ES" then
...
else

end if
