### ISSUE TITLE
Doesn't seem to work on Sequoia

### ISSUE THREAD

**Issue by LoiLock** [dustinsterk/AirPlayNotification-AutoApprove#4]
I updated our office mac mini to MacOS Sequoia, which we use as a receiver recently, and it no longer seems to work (launches just fine, but doesn't approve the request). Honestly have no idea where to start when it comes to debugging applescript.

All the permissions are set, and I didn't modify anything. I just used the .app file provided in the repo.

**Comment by dustinsterk** [comment]
Seeing the same after I upgraded...I will have to debug when I have some time.

**Comment by dustinsterk** [comment]
I have code that works, but needs more testing.  I cannot seem to find the notification window title so cannot only narrow this down to the AirPlay message:

use framework "Foundation"
use scripting additions

on idle
	try
		tell application "System Events" to tell application process "NotificationCenter"
			try
				perform (actions of UI elements of UI element 1 of scroll area 1 of group 1 of group 1 of window "Notification Center" of application process "NotificationCenter" of application "System Events" whose name starts with "Name:Accept")
			end try
		end tell
	end try
	return 2
end idle

**Comment by dustinsterk** [comment]
Added a new .app file in the repo and example code in the readme, ENJOY!

**Comment by LoiLock** [comment]
Thanks!

**Comment by dustinsterk** [comment]
Please let me know if you have any issues.
