### ISSUE TITLE
Sequoia script no longer working for Sequoia 15.1

### ISSUE THREAD

**Issue by bigadz** [dustinsterk/AirPlayNotification-AutoApprove#5]
The Sequoia specific applet was working just fine on Sequoia 15.0

I had previously used the drag'n drop solution, using this repo's `.app` directly in macOS 15.0.

After upgrading to macOS 15.1, the script no longer appears to work.

I have tried re-exporting from the Script editor, without success.

**Comment by dustinsterk** [comment]
I am not on 15.1, but will upgrade and see what apple broke now.  Its a never ending game of cat and mouse, very frustrating!

**Comment by dustinsterk** [comment]
Fixed with a new _15.1 app.

**Comment by bigadz** [comment]
Thank you!!

**Comment by bigadz** [comment]
Strange... This 15.1 script is not working for me. Let's see how others fair with it.

**Comment by dustinsterk** [comment]
Is your local language english on the machine?  Also ensure you remove the script from settings -> privacy and security -> accessibility.  Then when you run it again, it will re-add itself to the list and you need to toggle it back on again to give it permissions to "click".

**Comment by bigadz** [comment]
Ah thank you! 

I am using English, but I had not _removed_ the app from settings -> privacy and security -> accessibility. Now that I have, and re-run the app it is working.

**Comment by dustinsterk** [comment]
Glad to hear!

**Comment by dustinsterk** [comment]
@bigadz fyi I updated the script to check the notification window to look for the "accept" button as it was actioning other notifications in unexpected ways.
