### ISSUE TITLE
Doesn't click the dialog on Sequoia 15.2. Was having trouble in 15.1 too.

### ISSUE THREAD

**Issue by star-affinity** [dustinsterk/AirPlayNotification-AutoApprove#6]
I have tried turning off Screen Sharing and Remote Management. The script is approved in System Settings -> Privacy & Security -> Accessibility and it is running/open in the Dock in the but when the dialog to approve the connection comes up nothing happens.

Any ideas? I remember having it working Sonoma, but since Sequoia it's been a no go. I've even tried copying the script and manually creating an app (that was what was working in Sonoma).

Also asked both ChatGPT and Claude for assistance but nothing works.

Can't believe we can't have a list of always approved devices there in the AirPlay Receiver settings that can be removed if one wants. Damn it Apple! Good example of where too much security hampers usability.

**Comment by dustinsterk** [comment]
Have you used my updated scripts for Sequoia (see the main readme)?  There is a separate script for both 15.0 and 15.1.x as believe or not Apple changed the implementation even after the major OS update.

**Comment by star-affinity** [comment]
Thanks Dustin, but yes, I've tried the 15.1 script both using the app provided and creating my own app based on the 15.1 script you provide.

Maybe Apple has done something with 15.2 that makes the script not work again, or is it working for you on MacOS Sequoia 15.2?

**Comment by dustinsterk** [comment]
Oh sorry, I just realized I am not on 15.2 yet.  I will update and give it a look.  Maybe they did change things again!

**Comment by dustinsterk** [comment]
Yep, broke again in 15.2.  Ugh, will have to investiate.

**Comment by dustinsterk** [comment]
Fixed.  Updated Readme and also added a drag and drop solution.
